name: Profile cbds and simplex using optiprofiler, big

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow manually
  # schedule:
  # - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  test:
    name: Profile BDS and fminsearch, big
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [big]
        with_optim_toolbox: [yes]
        solver: [cbds]
        competitor: [fminsearch]
        run_plain: [false]
        feature: [noisy_1e-1, rotation_noisy_1e-1]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout OptiProfiler
        uses: actions/checkout@v4
        with:
          repository: optiprofiler/optiprofiler
          ref: matlab
          path: optiprofiler
      
      - name: Checkout BDS
        uses: actions/checkout@v4
        with:
          repository: blockwise-direct-search/bds
          ref: main
          path: bds

      - name: Install Texlive
        run: sudo apt-get update && sudo apt-get install texlive

      - name: Check whether LaTeX is installed
        run: pdflatex --version

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4.0.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox
      

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
            command: |
              root_dir = pwd()
              ls
  
              % Setup optiprofiler
              cd(fullfile(root_dir, 'optiprofiler'));
              setup
              cd(root_dir);
  
              % Setup bds
              cd(fullfile(root_dir, 'bds'));
              setup
              cd(fullfile(root_dir, 'bds', 'tests', 'competitors'));
              addpath(pwd);
  
              % profile
              cd(fullfile(root_dir, 'bds', 'tests'));
              options = struct();
              options.feature_name = '${{ matrix.feature }}';
              options.labels = {'${{ matrix.solver }}', '${{ matrix.competitor }}'};
              options.dim = '${{ matrix.dim }}';
              options = rmfield(options, 'dim');
              options.mindim = 1;
              options.maxdim = 2;
              options.n_runs = 1;
              options.run_plain = ${{ matrix.run_plain }};
              profile_optiprofiler(options);
              cd(root_dir);
              cd(fullfile(root_dir, 'bds', 'tests', 'out'));
              ls -R


      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: profile_optiprofiler_${{ matrix.solver }}_${{ matrix.competitor }}_${{ matrix.dim }}_${{ matrix.feature }}_${{ matrix.run_plain }}
          path: ./bds/tests/out/**

  merge_artifacts:
    name: Merge Artifacts
    runs-on: ubuntu-latest
    needs: test
    permissions:
      actions: read
      contents: read
    
    steps:
      - name: Install PDF tools
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: downloaded_artifacts

      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          ls -R downloaded_artifacts/

      - name: Merge PDF files
        run: |
          cd downloaded_artifacts
          ls -R
          # mkdir summary
          # find . -type f -name 'summary*.pdf' -exec cp {} summary/ \;
          # cd summary
          # # Define keywords to search for PDF files
          # keywords=("plain"\
          # "noisy_1e-1_no_rotation"\
          # "noisy_1e-2_no_rotation"\
          # "noisy_1e-3_no_rotation"\
          # "noisy_1e-4_no_rotation"\
          # "permuted"\
          # "linearly_transformed"\
          # "rotation_noisy_1e-1"\
          # "rotation_noisy_1e-2"\
          # "rotation_noisy_1e-3"\
          # "rotation_noisy_1e-4"\
          # "quantized"\
          # "perturbed_x0"\
          # "random_nan_5"\
          # "random_nan_10"\
          # "random_nan_20"\
          # "truncated_1"\
          # "truncated_2"\
          # "truncated_3"\
          # "truncated_4")

          # output_file="merged.pdf"
          # declare -a pdf_files  # Use an array to store PDF files

          # # Loop through each keyword
          # for keyword in "${keywords[@]}"; do
          #     # Find PDF files with the keyword
          #     for file in *"$keyword"*.pdf; do
          #         if [[ -f "$file" && ! " ${pdf_files[*]} " =~ " $file " ]]; then  # Check if the file exists and is not already in the array
          #             pdf_files+=("$file")
          #         fi
          #     done
          # done

          # # Merge PDF files
          # if [[ ${#pdf_files[@]} -gt 0 ]]; then
          #     pdfunite "${pdf_files[@]}" "$output_file"
          #     echo "Merge successfully: $output_file"
          # else
          #     echo "There are no PDF files to merge."
          # fi

      - name: Upload merged artifact
        uses: actions/upload-artifact@v3
        with:
          name: merged_profiles
          path: downloaded_artifacts
