name: Profile Test Workflow

on:
  push:
  workflow_dispatch:

env:
  GFORTRAN_VERSION: 12

jobs:
  test:
    name: Profile ${{ matrix.solver }} with competitor ${{ matrix.competitor }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [small]
        with_optim_toolbox: [yes]
        solver: [cbds]
        competitor: [fminunc]
        run_plain: [true, false]
        feature: [plain]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout OptiProfiler
        uses: actions/checkout@v4
        with:
          repository: optiprofiler/optiprofiler
          ref: matlab
          path: optiprofiler
      
      - name: Checkout BDS
        uses: actions/checkout@v4
        with:
          repository: blockwise-direct-search/bds
          ref: main
          path: bds

      - name: Install Texlive
        run: sudo apt-get update && sudo apt-get install -y texlive

      - name: Check whether LaTeX is installed
        run: pdflatex --version

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4.0.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            root_dir = pwd();
            ls;

            % Setup optiprofiler
            cd(fullfile(root_dir, 'optiprofiler'));
            setup;
            cd(root_dir);

            % Setup bds
            cd(fullfile(root_dir, 'bds'));
            setup;
            cd(fullfile(root_dir, 'bds', 'tests', 'competitors'));
            addpath(pwd);

            % Profile
            cd(fullfile(root_dir, 'bds', 'tests'));
            options = struct();
            options.feature_name = '${{ matrix.feature }}';
            options.labels = {'${{ matrix.solver }}', '${{ matrix.competitor }}'};
            options.dim = '${{ matrix.dim }}';
            options = rmfield(options, 'dim');
            options.mindim = 1;
            options.maxdim = 1;
            options.run_plain = ${{ matrix.run_plain }};
            profile_optiprofiler(options);
            cd(root_dir);

      - name: Check output before upload
        run: ls -R ./bds/tests/out

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: profile_optiprofiler_${{ matrix.solver }}_${{ matrix.competitor }}_${{ matrix.dim }}_${{ matrix.feature }}_plain_${{ matrix.run_plain }}
          path: ./bds/tests/out

  download_and_upload:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create directory for downloaded artifacts
        run: mkdir -p ./downloaded_artifacts

      - name: Download Artifacts
        run: |
          for run_plain in true false; do
            artifact_name="profile_optiprofiler_cbds_fminunc_small_plain_${run_plain}"
            echo "Downloading artifact: $artifact_name"
            actions/download-artifact@v3 --name "$artifact_name" --path ./downloaded_artifacts/ || echo "Artifact $artifact_name not found."
          done

      - name: Consolidate artifacts
        run: |
          mkdir -p ./final_artifacts
          mv ./downloaded_artifacts/* ./final_artifacts/

      - name: Upload consolidated artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: consolidated_artifact
          path: ./final_artifacts/