name: Profile Test Workflow

on:
  push:
  workflow_dispatch:

env:
  GFORTRAN_VERSION: 12

jobs:
  test:
    name: Profile ${{ matrix.solver }} with competitor ${{ matrix.competitor }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [small]
        with_optim_toolbox: [yes]
        solver: [cbds]
        competitor: [fminunc]
        run_plain: [true, false]
        feature: [plain]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout OptiProfiler
        uses: actions/checkout@v4
        with:
          repository: optiprofiler/optiprofiler
          ref: matlab
          path: optiprofiler
      
      - name: Checkout BDS
        uses: actions/checkout@v4
        with:
          repository: blockwise-direct-search/bds
          ref: main
          path: bds

      - name: Install Texlive
        run: sudo apt-get update && sudo apt-get install -y texlive

      - name: Check whether LaTeX is installed
        run: pdflatex --version

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4.0.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            root_dir = pwd();
            % Setup optiprofiler
            cd(fullfile(root_dir, 'optiprofiler'));
            setup;
            cd(root_dir);

            % Setup bds
            cd(fullfile(root_dir, 'bds'));
            setup;
            cd(fullfile(root_dir, 'bds', 'tests', 'competitors'));
            addpath(pwd);

            % Profile
            cd(fullfile(root_dir, 'bds', 'tests'));
            options = struct();
            options.feature_name = '${{ matrix.feature }}';
            options.labels = {'${{ matrix.solver }}', '${{ matrix.competitor }}'};
            options.dim = '${{ matrix.dim }}';
            options = rmfield(options, 'dim');
            options.mindim = 1;
            options.maxdim = 1;
            options.run_plain = ${{ matrix.run_plain }};
            profile_optiprofiler(options);
            cd(root_dir);

      - name: Check output before upload
        run: ls -R ./bds/tests/out

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: profile_optiprofiler_${{ matrix.solver }}_${{ matrix.competitor }}_${{ matrix.dim }}_${{ matrix.feature }}_plain_${{ matrix.run_plain }}
          path: ./bds/tests/out

      - name: Set artifact name output
        id: set_output
        run: echo "ARTIFACT_NAME=profile_optiprofiler_${{ matrix.solver }}_${{ matrix.competitor }}_${{ matrix.dim }}_${{ matrix.feature }}_plain_${{ matrix.run_plain }}" >> $GITHUB_ENV

  merge_artifacts:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        run: |
          echo "Downloading artifacts..."
          mkdir -p ./merged_artifacts

          for run_plain in true false; do
            artifact_name="profile_optiprofiler_${matrix.solver}_${matrix.competitor}_${matrix.dim}_${matrix.feature}_plain_${run_plain}"
            echo "Artifact name: $artifact_name"
            artifact_id=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r ".artifacts[] | select(.name == \"$artifact_name\") | .id")

            if [ -z "$artifact_id" ]; then
              echo "Artifact $artifact_name not found!"
              continue
            fi

            download_url="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip"
            echo "Downloading from URL: $download_url"
            curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -o "./merged_artifacts/$artifact_name.zip" "$download_url"
          done

      - name: Unzip downloaded artifacts
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          for zip_file in ./merged_artifacts/*.zip; do
            unzip "$zip_file" -d ./merged_artifacts
          done

      - name: Merge artifacts
        run: |
          mkdir -p ./final_output
          cp -r ./merged_artifacts/* ./final_output/
          # 可以根据需要添加合并逻辑，例如合并文件、生成报告等

      - name: Upload merged artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: merged_profile_artifacts
          path: ./final_output